on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Preprocess
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        path: app
        node-version: 16
    - run: npm run preprocess
